export { Home } from './home'
export { Manage } from './manage'
export { NewStake } from './manage/new/newStake'
export { Documentation } from './documentation'
export { Wrap } from './wrap'
export { SimplePRE } from './simplePRE'